apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
spec:
  selector:
    matchLabels:
      app: backend1
  replicas: 1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend1
        image: ravianxreaver/go_service1:v2
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 10001